### ISSUE TITLE
Compatibility issues with this shape file reader

### ISSUE THREAD

**Issue by davidliu0305** [xfischer/ShapeFileReader#1]
Thank you for your shape file reading solution. Since the ASP.net core has made lots of changes on its own libraries, I have made some changes on this shape file reader which allow users to read the shape file, spatial index file and DBF file from the memory stream which will make things a lot easier. We can create a memory stream from the zipped file (which has .shp, .shx and .dbf inside) and read all the info from these 3 files.  My solution is compatible with both .net framework and .net core and it does not require OLEDB connection for DBF reader.  CSV reader is also included in my solution.  I will share my solution here. 

I also incorporated part of the source code from the solutions of two other authors on Github:
https://gist.github.com/sleimanzublidi/27acd30b5d4b452d5ec6
https://github.com/yallie/unzip/blob/master/Unzip.cs

This is my solution. 
[Shiqian-shapefile-reader3-thisshouldwork (2).zip](https://github.com/xfischer/ShapeFileReader/files/1254669/Shiqian-shapefile-reader3-thisshouldwork.2.zip)

**Comment by xfischer** [comment]
Thanks @davidliu0305. Il not with my PC now, I will see your solution soon. Can you do a pull request in order to see a clean and complete integration of your propositions ?

**Comment by xfischer** [comment]
I have invited you on Gitter to talk about this.

**Comment by xfischer** [comment]
OK. I have rebased with your solution. Thank you.

One thing is missing : the projection (optionnal) from .PRJ file if present. Will try to add this in the future.
